//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Enum", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string booking_type_calendar {
            get {
                return ResourceManager.GetString("booking_type_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Booking.
        /// </summary>
        internal static string booking_type_online {
            get {
                return ResourceManager.GetString("booking_type_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string channel_offline {
            get {
                return ResourceManager.GetString("channel_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string channel_online {
            get {
                return ResourceManager.GetString("channel_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Date.
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Email.
        /// </summary>
        internal static string email_cancellation_booking_client {
            get {
                return ResourceManager.GetString("email_cancellation_booking_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Email.
        /// </summary>
        internal static string email_confirmation_booking_client {
            get {
                return ResourceManager.GetString("email_confirmation_booking_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Email.
        /// </summary>
        internal static string email_invoice {
            get {
                return ResourceManager.GetString("email_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Email.
        /// </summary>
        internal static string email_reminder_booking_client {
            get {
                return ResourceManager.GetString("email_reminder_booking_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduling Email.
        /// </summary>
        internal static string email_rescheduling_booking_client {
            get {
                return ResourceManager.GetString("email_rescheduling_booking_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You Email.
        /// </summary>
        internal static string email_thank_you_booking_client {
            get {
                return ResourceManager.GetString("email_thank_you_booking_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of this month.
        /// </summary>
        internal static string end_of_month {
            get {
                return ResourceManager.GetString("end_of_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string gender_female {
            get {
                return ResourceManager.GetString("gender_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string gender_male {
            get {
                return ResourceManager.GetString("gender_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string gender_unknown {
            get {
                return ResourceManager.GetString("gender_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string invoice_status_complete {
            get {
                return ResourceManager.GetString("invoice_status_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Paid.
        /// </summary>
        internal static string invoice_status_part_paid {
            get {
                return ResourceManager.GetString("invoice_status_part_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string invoice_status_refund {
            get {
                return ResourceManager.GetString("invoice_status_refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        internal static string invoice_status_unpaid {
            get {
                return ResourceManager.GetString("invoice_status_unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        internal static string invoice_status_void {
            get {
                return ResourceManager.GetString("invoice_status_void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string invoice_type_refund {
            get {
                return ResourceManager.GetString("invoice_type_refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string invoice_type_sale {
            get {
                return ResourceManager.GetString("invoice_type_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Voucher.
        /// </summary>
        internal static string item_type_gift_voucher {
            get {
                return ResourceManager.GetString("item_type_gift_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string item_type_product {
            get {
                return ResourceManager.GetString("item_type_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string item_type_service {
            get {
                return ResourceManager.GetString("item_type_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Voucher.
        /// </summary>
        internal static string item_type_service_voucher {
            get {
                return ResourceManager.GetString("item_type_service_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        internal static string item_type_total_sale {
            get {
                return ResourceManager.GetString("item_type_total_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &amp; SMS.
        /// </summary>
        internal static string marketing_both {
            get {
                return ResourceManager.GetString("marketing_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string marketing_email {
            get {
                return ResourceManager.GetString("marketing_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t send notifications.
        /// </summary>
        internal static string marketing_none {
            get {
                return ResourceManager.GetString("marketing_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string marketing_sms {
            get {
                return ResourceManager.GetString("marketing_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounced.
        /// </summary>
        internal static string message_status_bounced {
            get {
                return ResourceManager.GetString("message_status_bounced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string message_status_sending {
            get {
                return ResourceManager.GetString("message_status_sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string message_status_sent {
            get {
                return ResourceManager.GetString("message_status_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        internal static string months_1 {
            get {
                return ResourceManager.GetString("months_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Months.
        /// </summary>
        internal static string months_2 {
            get {
                return ResourceManager.GetString("months_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Months.
        /// </summary>
        internal static string months_3 {
            get {
                return ResourceManager.GetString("months_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Months.
        /// </summary>
        internal static string months_6 {
            get {
                return ResourceManager.GetString("months_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Expiry.
        /// </summary>
        internal static string never {
            get {
                return ResourceManager.GetString("never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All statuses.
        /// </summary>
        internal static string order_status_all {
            get {
                return ResourceManager.GetString("order_status_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string order_status_canceled {
            get {
                return ResourceManager.GetString("order_status_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered.
        /// </summary>
        internal static string order_status_ordered {
            get {
                return ResourceManager.GetString("order_status_ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string order_status_received {
            get {
                return ResourceManager.GetString("order_status_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string order_type_order {
            get {
                return ResourceManager.GetString("order_type_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string order_type_transfer {
            get {
                return ResourceManager.GetString("order_type_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by channel.
        /// </summary>
        internal static string report_sale_by_channel {
            get {
                return ResourceManager.GetString("report_sale_by_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by client.
        /// </summary>
        internal static string report_sale_by_client {
            get {
                return ResourceManager.GetString("report_sale_by_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by day.
        /// </summary>
        internal static string report_sale_by_day {
            get {
                return ResourceManager.GetString("report_sale_by_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by hour.
        /// </summary>
        internal static string report_sale_by_hour {
            get {
                return ResourceManager.GetString("report_sale_by_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by item.
        /// </summary>
        internal static string report_sale_by_item {
            get {
                return ResourceManager.GetString("report_sale_by_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by location.
        /// </summary>
        internal static string report_sale_by_location {
            get {
                return ResourceManager.GetString("report_sale_by_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by month.
        /// </summary>
        internal static string report_sale_by_month {
            get {
                return ResourceManager.GetString("report_sale_by_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by product.
        /// </summary>
        internal static string report_sale_by_product {
            get {
                return ResourceManager.GetString("report_sale_by_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by quarter.
        /// </summary>
        internal static string report_sale_by_quarter {
            get {
                return ResourceManager.GetString("report_sale_by_quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by service.
        /// </summary>
        internal static string report_sale_by_service {
            get {
                return ResourceManager.GetString("report_sale_by_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by staff.
        /// </summary>
        internal static string report_sale_by_staff {
            get {
                return ResourceManager.GetString("report_sale_by_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by type.
        /// </summary>
        internal static string report_sale_by_type {
            get {
                return ResourceManager.GetString("report_sale_by_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by year.
        /// </summary>
        internal static string report_sale_by_year {
            get {
                return ResourceManager.GetString("report_sale_by_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string stock_adjustment {
            get {
                return ResourceManager.GetString("stock_adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string stock_adjustment_decrease {
            get {
                return ResourceManager.GetString("stock_adjustment_decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged.
        /// </summary>
        internal static string stock_damaged {
            get {
                return ResourceManager.GetString("stock_damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal use.
        /// </summary>
        internal static string stock_internal {
            get {
                return ResourceManager.GetString("stock_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string stock_invoice {
            get {
                return ResourceManager.GetString("stock_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string stock_invoice_refund {
            get {
                return ResourceManager.GetString("stock_invoice_refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        internal static string stock_invoice_void {
            get {
                return ResourceManager.GetString("stock_invoice_void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stock.
        /// </summary>
        internal static string stock_new_stock {
            get {
                return ResourceManager.GetString("stock_new_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string stock_other {
            get {
                return ResourceManager.GetString("stock_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string stock_other_decrease {
            get {
                return ResourceManager.GetString("stock_other_decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of date.
        /// </summary>
        internal static string stock_out_of_date {
            get {
                return ResourceManager.GetString("stock_out_of_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string stock_return {
            get {
                return ResourceManager.GetString("stock_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string stock_transfer {
            get {
                return ResourceManager.GetString("stock_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string stock_transfer_decrease {
            get {
                return ResourceManager.GetString("stock_transfer_decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string voucher_stattus_expired {
            get {
                return ResourceManager.GetString("voucher_stattus_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed.
        /// </summary>
        internal static string voucher_status_redeemed {
            get {
                return ResourceManager.GetString("voucher_status_redeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded Invoice.
        /// </summary>
        internal static string voucher_status_refunded_invoice {
            get {
                return ResourceManager.GetString("voucher_status_refunded_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        internal static string voucher_status_unpaid {
            get {
                return ResourceManager.GetString("voucher_status_unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string voucher_status_valid {
            get {
                return ResourceManager.GetString("voucher_status_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift voucher.
        /// </summary>
        internal static string voucher_type_gift_voucher {
            get {
                return ResourceManager.GetString("voucher_type_gift_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service voucher.
        /// </summary>
        internal static string voucher_type_service_voucher {
            get {
                return ResourceManager.GetString("voucher_type_service_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Year.
        /// </summary>
        internal static string years_1 {
            get {
                return ResourceManager.GetString("years_1", resourceCulture);
            }
        }
    }
}
