//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Function {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Function() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Function", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access All Locations.
        /// </summary>
        internal static string access_all_location {
            get {
                return ResourceManager.GetString("access_all_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Setup.
        /// </summary>
        internal static string account_setup {
            get {
                return ResourceManager.GetString("account_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Reports.
        /// </summary>
        internal static string all_reports {
            get {
                return ResourceManager.GetString("all_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string appointments {
            get {
                return ResourceManager.GetString("appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can delete invoices.
        /// </summary>
        internal static string can_delete_invoices {
            get {
                return ResourceManager.GetString("can_delete_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can download clients.
        /// </summary>
        internal static string can_download_clients {
            get {
                return ResourceManager.GetString("can_download_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Settings.
        /// </summary>
        internal static string client_settings {
            get {
                return ResourceManager.GetString("client_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Dates.
        /// </summary>
        internal static string closed_dates {
            get {
                return ResourceManager.GetString("closed_dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Sales.
        /// </summary>
        internal static string daily_sales {
            get {
                return ResourceManager.GetString("daily_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        internal static string invoices {
            get {
                return ResourceManager.GetString("invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Booking.
        /// </summary>
        internal static string online_booking {
            get {
                return ResourceManager.GetString("online_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Staff Calendars.
        /// </summary>
        internal static string other_staff_calendars {
            get {
                return ResourceManager.GetString("other_staff_calendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Calendar.
        /// </summary>
        internal static string own_calendar {
            get {
                return ResourceManager.GetString("own_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Levels.
        /// </summary>
        internal static string permission_levels {
            get {
                return ResourceManager.GetString("permission_levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Sale.
        /// </summary>
        internal static string point_of_sale {
            get {
                return ResourceManager.GetString("point_of_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Members.
        /// </summary>
        internal static string staff_members {
            get {
                return ResourceManager.GetString("staff_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        internal static string vouchers {
            get {
                return ResourceManager.GetString("vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        internal static string working_hours {
            get {
                return ResourceManager.GetString("working_hours", resourceCulture);
            }
        }
    }
}
