//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentService
    {
        public long AppointmentServiceID { get; set; }
        public long AppointmentID { get; set; }
        public long BusinessID { get; set; }
        public string RefNo { get; set; }
        public long ServiceID { get; set; }
        public string ServiceName { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal SpecialPrice { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartTime { get; set; }
        public int Duration { get; set; }
        public long StaffID { get; set; }
        public Nullable<long> ResourceID { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int SortOrder { get; set; }
        public bool IsRequest { get; set; }
    }
}
