//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentID { get; set; }
        public long BusinessID { get; set; }
        public string BookingType { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public Nullable<long> ClientID { get; set; }
        public string ClientName { get; set; }
        public long LocationID { get; set; }
        public decimal TotalAmount { get; set; }
        public int TotalTimeInMinutes { get; set; }
        public string Status { get; set; }
        public string ReasonCancel { get; set; }
        public Nullable<System.DateTime> DatetimeCancel { get; set; }
        public Nullable<long> UserCancel { get; set; }
        public string FrequencyType { get; set; }
        public string RepeatCount { get; set; }
        public Nullable<System.DateTime> EndRepeat { get; set; }
        public string Notes { get; set; }
        public long UserCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<long> ParentAppointmentID { get; set; }
        public Nullable<int> RepeatOrder { get; set; }
    }
}
