//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long ClientID { get; set; }
        public long BusinessID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string AppointmentNotificationType { get; set; }
        public bool AcceptMarketingNotifications { get; set; }
        public string Gender { get; set; }
        public Nullable<long> ReferralSource { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ClientNotes { get; set; }
        public bool DisplayOnAllBookings { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public int Appointments { get; set; }
        public int NoShows { get; set; }
        public decimal TotalSales { get; set; }
        public decimal Outstanding { get; set; }
        public string LastLocation { get; set; }
        public long UserCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string MobileNumberDialCode { get; set; }
        public string TelephoneDialCode { get; set; }
        public Nullable<System.DateTime> LastAppointment { get; set; }
    }
}
