//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public int SortOrder { get; set; }
        public string CurrencyCode { get; set; }
        public string TimeZone { get; set; }
        public string CountryCode { get; set; }
        public string DialCode { get; set; }
        public string TimeZoneMS { get; set; }
    }
}
