//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public long InvoicePaymentID { get; set; }
        public long InvoiceID { get; set; }
        public long BusinessID { get; set; }
        public long PaymentTypeID { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public long UserPayment { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<long> VoucherID { get; set; }
        public Nullable<long> PayForServiceID { get; set; }
    }
}
