//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public long InvoiceDetailID { get; set; }
        public long InvoiceID { get; set; }
        public long BusinessID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal SpecialPrice { get; set; }
        public string DiscountName { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal Price { get; set; }
        public Nullable<long> TaxID { get; set; }
        public decimal TaxRate { get; set; }
        public decimal TaxAmount { get; set; }
        public int Quantity { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public long StaffID { get; set; }
        public Nullable<long> ResourceID { get; set; }
        public decimal PriceBeforeTax { get; set; }
        public decimal SubTotalBeForeTax { get; set; }
        public bool EnableCommission { get; set; }
        public Nullable<long> DiscountID { get; set; }
        public Nullable<System.DateTime> VoucherExpiryDate { get; set; }
        public decimal PriceAfterDiscount { get; set; }
        public decimal CostPrice { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalTax { get; set; }
        public decimal Total { get; set; }
        public string TaxType { get; set; }
        public Nullable<long> AppointmentServiceID { get; set; }
        public decimal CommissionRate { get; set; }
    }
}
