//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public long LocationID { get; set; }
        public long BusinessID { get; set; }
        public string LocationName { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public string StreetAddress { get; set; }
        public string APT { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public bool EnableOnlineBooking { get; set; }
        public bool IsDefault { get; set; }
        public long UserCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string InvoiceNoPrefix { get; set; }
        public long NextInvoiceNumber { get; set; }
        public int SortOrder { get; set; }
    }
}
