//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogException
    {
        public long ExceptionID { get; set; }
        public long BusinessID { get; set; }
        public long UserID { get; set; }
        public System.DateTime ExceptionTime { get; set; }
        public string FunctioName { get; set; }
        public string URL { get; set; }
        public string ExceptionDetail { get; set; }
    }
}
