//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntity : DbContext
    {
        public ModelEntity()
            : base("name=ModelEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessType> BusinessTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<TimeZone> TimeZones { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<ResetPassword> ResetPasswords { get; set; }
        public virtual DbSet<TimeFormat> TimeFormats { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<DefaultColor> DefaultColors { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatusUser> StatusUsers { get; set; }
        public virtual DbSet<TreatmentType> TreatmentTypes { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ServiceGroup> ServiceGroups { get; set; }
        public virtual DbSet<Dial_Code> Dial_Code { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceDuration> ServiceDurations { get; set; }
        public virtual DbSet<ServiceStaff> ServiceStaffs { get; set; }
        public virtual DbSet<Duration> Durations { get; set; }
        public virtual DbSet<AvailableFor> AvailableFors { get; set; }
        public virtual DbSet<AppointmentColor> AppointmentColors { get; set; }
        public virtual DbSet<ExtraTimeType> ExtraTimeTypes { get; set; }
        public virtual DbSet<PricingType> PricingTypes { get; set; }
        public virtual DbSet<TimeSlotInterval> TimeSlotIntervals { get; set; }
        public virtual DbSet<Tooltip> Tooltips { get; set; }
        public virtual DbSet<VoucherExpiryPeriod> VoucherExpiryPeriods { get; set; }
        public virtual DbSet<CancellationReason> CancellationReasons { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<ReferralSource> ReferralSources { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TaxLocation> TaxLocations { get; set; }
        public virtual DbSet<ServiceResource> ServiceResources { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLocation> UserLocations { get; set; }
        public virtual DbSet<UserWorkingHour> UserWorkingHours { get; set; }
        public virtual DbSet<ClosedDate> ClosedDates { get; set; }
        public virtual DbSet<ClosedDate_Location> ClosedDate_Location { get; set; }
        public virtual DbSet<BusinessSetting> BusinessSettings { get; set; }
        public virtual DbSet<LogException> LogExceptions { get; set; }
        public virtual DbSet<LangString> LangStrings { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<AppointmentService> AppointmentServices { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<PermissionLevel> PermissionLevels { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductStockMovement> ProductStockMovements { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<InvoicePayment> InvoicePayments { get; set; }
        public virtual DbSet<InvoiceTip> InvoiceTips { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<ProductLocation> ProductLocations { get; set; }
        public virtual DbSet<V_PRODUCT> V_PRODUCT { get; set; }
        public virtual DbSet<V_PRODUCT_BUSINESS> V_PRODUCT_BUSINESS { get; set; }
        public virtual DbSet<V_SERVICE> V_SERVICE { get; set; }
        public virtual DbSet<V_PRODUCT_STOCK_MOVEMENT> V_PRODUCT_STOCK_MOVEMENT { get; set; }
        public virtual DbSet<V_ORDER> V_ORDER { get; set; }
        public virtual DbSet<BlockTime> BlockTimes { get; set; }
        public virtual DbSet<V_INVOICE_PAYMENT> V_INVOICE_PAYMENT { get; set; }
        public virtual DbSet<V_CLIENT> V_CLIENT { get; set; }
        public virtual DbSet<V_TBL_USER_WORKING_HOUR> V_TBL_USER_WORKING_HOUR { get; set; }
        public virtual DbSet<V_VOUCHER> V_VOUCHER { get; set; }
        public virtual DbSet<V_APPOINTMENT_SERVICE> V_APPOINTMENT_SERVICE { get; set; }
        public virtual DbSet<V_TBL_APPOINTMENT_SERVICE> V_TBL_APPOINTMENT_SERVICE { get; set; }
        public virtual DbSet<V_INVOICE_DETAIL> V_INVOICE_DETAIL { get; set; }
        public virtual DbSet<V_INVOICE> V_INVOICE { get; set; }
        public virtual DbSet<TBL_SMS> TBL_SMS { get; set; }
        public virtual DbSet<TBL_APPOINTMENT_REMINDER> TBL_APPOINTMENT_REMINDER { get; set; }
        public virtual DbSet<V_BUSINESS> V_BUSINESS { get; set; }
        public virtual DbSet<SYS_PACKAGE> SYS_PACKAGE { get; set; }
        public virtual DbSet<V_APPOINTMENT_REMINDER> V_APPOINTMENT_REMINDER { get; set; }
        public virtual DbSet<V_MESSAGE> V_MESSAGE { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<UpdateHistory> UpdateHistories { get; set; }
    }
}
