//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public long OrderProductID { get; set; }
        public long OrderID { get; set; }
        public long BusinessID { get; set; }
        public long ProductID { get; set; }
        public int Quantity { get; set; }
        public int ReceivedQuantity { get; set; }
        public decimal SupplyPrice { get; set; }
        public decimal TotalCost { get; set; }
    }
}
