//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderID { get; set; }
        public long BusinessID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string OrderType { get; set; }
        public long LocationID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> FromLocationID { get; set; }
        public string OrderStatus { get; set; }
        public decimal TotalCost { get; set; }
        public long UserCreate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<long> UserCancel { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<long> UserReceive { get; set; }
    }
}
