//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionLevel
    {
        public string FormCode { get; set; }
        public long BusinessID { get; set; }
        public bool Low { get; set; }
        public bool Medium { get; set; }
        public bool High { get; set; }
        public bool Owner { get; set; }
    }
}
