//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductID { get; set; }
        public long BusinessID { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> BrandID { get; set; }
        public string Barcode { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public bool EnableRetailSales { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal SpecialPrice { get; set; }
        public Nullable<long> TaxID { get; set; }
        public decimal TaxRate { get; set; }
        public bool EnableCommission { get; set; }
        public bool EnableStockControl { get; set; }
        public decimal SupplyPrice { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public long UserCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
