//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPassword
    {
        public System.Guid ResetID { get; set; }
        public long UserID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime ExpriredDate { get; set; }
        public bool IsUsed { get; set; }
    }
}
