//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDuration
    {
        public long ServiceDurationID { get; set; }
        public long ServiceID { get; set; }
        public long BusinessID { get; set; }
        public int Duration { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal SpecialPrice { get; set; }
        public string Caption { get; set; }
        public long UserCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
