//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public long SupplierID { get; set; }
        public long BusinessID { get; set; }
        public string SupplierName { get; set; }
        public string Description { get; set; }
        public string FirtName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Website { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryID { get; set; }
        public bool SameAsPostalAddress { get; set; }
        public string PStreet { get; set; }
        public string PSuburb { get; set; }
        public string PCity { get; set; }
        public string PState { get; set; }
        public Nullable<int> PCountryID { get; set; }
        public long UserCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ZipCode { get; set; }
        public string PZipCode { get; set; }
        public int ProductAssigned { get; set; }
        public bool IsDelete { get; set; }
    }
}
