//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SMS
    {
        public long SMSID { get; set; }
        public long BusinessID { get; set; }
        public long AppointmentID { get; set; }
        public string PhoneNumber { get; set; }
        public string Body { get; set; }
        public string MessageId { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public bool IsSent { get; set; }
        public int Retry { get; set; }
    }
}
