//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public int TimeZoneID { get; set; }
        public string TimeZoneName { get; set; }
        public int SortOrder { get; set; }
        public string TimeZoneCode { get; set; }
        public string TimeZone1 { get; set; }
        public int TimeZoneInMinute { get; set; }
    }
}
