//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkingHour
    {
        public long BusinessID { get; set; }
        public long LocationID { get; set; }
        public long UserID { get; set; }
        public short DayOfWeek { get; set; }
        public System.DateTime DateWorking { get; set; }
        public System.DateTime Shift1Start { get; set; }
        public System.DateTime Shift1End { get; set; }
        public Nullable<System.DateTime> Shift2Start { get; set; }
        public Nullable<System.DateTime> Shift2End { get; set; }
        public int BreakTimeInMinutes { get; set; }
        public bool IsRepeat { get; set; }
        public string RepeatType { get; set; }
        public Nullable<System.DateTime> EndRepeat { get; set; }
        public int WorkingTimeInMinutes { get; set; }
    }
}
