//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APPOINTMENT_SERVICE
    {
        public long AppointmentServiceID { get; set; }
        public long AppointmentID { get; set; }
        public long BusinessID { get; set; }
        public string RefNo { get; set; }
        public long ServiceID { get; set; }
        public string ServiceName { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal SpecialPrice { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int Duration { get; set; }
        public long StaffID { get; set; }
        public Nullable<long> ResourceID { get; set; }
        public string DurationName { get; set; }
        public bool EnableCommission { get; set; }
        public long TaxID { get; set; }
        public decimal TaxRate { get; set; }
        public string LocationName { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string StaffName { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> TotalTimeInMinutes { get; set; }
        public string Status { get; set; }
        public string ReasonCancel { get; set; }
        public Nullable<System.DateTime> DatetimeCancel { get; set; }
        public string RepeatCount { get; set; }
        public Nullable<System.DateTime> EndRepeat { get; set; }
        public string Notes { get; set; }
        public Nullable<long> ClientID { get; set; }
        public string BookingType { get; set; }
        public Nullable<int> StartTimeInSecond { get; set; }
        public bool IsRequest { get; set; }
        public string ScheduledDateString { get; set; }
        public string StartTimeString { get; set; }
        public string EndTimeString { get; set; }
    }
}
