//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BUSINESS
    {
        public long BusinessID { get; set; }
        public string CompanyName { get; set; }
        public int BusinessTypeID { get; set; }
        public int CountryID { get; set; }
        public int TimeZoneID { get; set; }
        public string CurrencyCode { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string ContactNumberDialCode { get; set; }
        public string ContactNumber { get; set; }
        public string TimeFormat { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int PackageID { get; set; }
        public string Language { get; set; }
        public string CountryName { get; set; }
        public string BusinessTypeName { get; set; }
        public string Expiry { get; set; }
        public string PackageName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}
