//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVOICE_DETAIL
    {
        public long InvoiceID { get; set; }
        public long BusinessID { get; set; }
        public Nullable<long> AppointmentID { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceStatus { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public long LocationID { get; set; }
        public Nullable<long> ClientID { get; set; }
        public string ClientName { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalTax { get; set; }
        public decimal TipAmount { get; set; }
        public decimal Total { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal Balance { get; set; }
        public decimal Change { get; set; }
        public Nullable<long> PaymentReceivedBy { get; set; }
        public string Notes { get; set; }
        public long UserCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Channel { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> SpecialPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> DiscountID { get; set; }
        public string DiscountName { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> PriceAfterDiscount { get; set; }
        public Nullable<decimal> PriceBeforeTax { get; set; }
        public Nullable<long> TaxID { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SubTotalDetail { get; set; }
        public Nullable<decimal> SubTotalBeForeTaxDetail { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<long> StaffID { get; set; }
        public Nullable<long> ResourceID { get; set; }
        public Nullable<bool> EnableCommission { get; set; }
        public Nullable<System.DateTime> VoucherExpiryDate { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public decimal SubTotalBeForeTax { get; set; }
        public Nullable<decimal> TotalDiscountDetail { get; set; }
        public Nullable<decimal> TotalTaxDetail { get; set; }
        public decimal TotalWithTip { get; set; }
        public Nullable<decimal> TotalDetail { get; set; }
        public string TaxType { get; set; }
        public Nullable<System.DateTime> StartTimeAPSService { get; set; }
        public string StaffAPSService { get; set; }
        public string Barcode { get; set; }
        public string StaffIV { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<long> AppointmentServiceID { get; set; }
        public decimal VoucherValue { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public bool EnableStockControl { get; set; }
        public string DurationName { get; set; }
        public Nullable<long> InvoiceDetailID { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> TotalDiscountDetailExcludeTax { get; set; }
        public Nullable<decimal> PriceExcludeTax { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public string InvoiceDateString { get; set; }
        public string DueDateString { get; set; }
        public string CreateDateString { get; set; }
        public string ModifyDateString { get; set; }
        public string VoucherExpiryDateString { get; set; }
        public string StartTimeAPSServiceString { get; set; }
        public string ExpireDateString { get; set; }
        public string IssueDateString { get; set; }
        public string SKU { get; set; }
    }
}
