//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDER
    {
        public long OrderID { get; set; }
        public long BusinessID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long UserCreate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<long> UserCancel { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<long> UserReceive { get; set; }
        public string OrderType { get; set; }
        public long LocationID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> FromLocationID { get; set; }
        public string OrderStatus { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<long> UserModify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string LocationName { get; set; }
        public string FLocationName { get; set; }
        public string SupplierName { get; set; }
        public string Description { get; set; }
        public string FirtName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Website { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<bool> SameAsPostalAddress { get; set; }
        public string PStreet { get; set; }
        public string PSuburb { get; set; }
        public string PCity { get; set; }
        public string PState { get; set; }
        public string PZipCode { get; set; }
        public Nullable<int> PCountryID { get; set; }
        public Nullable<int> ProductAssigned { get; set; }
        public string TStreetAddress { get; set; }
        public string TAPT { get; set; }
        public string TCity { get; set; }
        public string TState { get; set; }
        public string TZipCode { get; set; }
        public string FStreetAddress { get; set; }
        public string FAPT { get; set; }
        public string FCity { get; set; }
        public string FState { get; set; }
        public string FZipCode { get; set; }
        public string StaffNameCreate { get; set; }
        public string StaffNameCancel { get; set; }
        public string StaffNameReceive { get; set; }
    }
}
