//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCT_STOCK_MOVEMENT
    {
        public long ProductStockMovementID { get; set; }
        public long BusinessID { get; set; }
        public long ProductID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public long LocationID { get; set; }
        public long UserCreate { get; set; }
        public string StockType { get; set; }
        public string Action { get; set; }
        public int Adjustment { get; set; }
        public decimal AdjustmentCost { get; set; }
        public decimal CostPrice { get; set; }
        public int OnHand { get; set; }
        public decimal OnHandCost { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public string LocationName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string SupplierName { get; set; }
        public string CategoryName { get; set; }
        public string TaxName { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> BrandID { get; set; }
        public string Barcode { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public Nullable<bool> EnableRetailSales { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> SpecialPrice { get; set; }
        public Nullable<long> TaxID { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<bool> EnableCommission { get; set; }
        public Nullable<bool> EnableStockControl { get; set; }
        public Nullable<decimal> SupplyPrice { get; set; }
        public string OrderNo { get; set; }
        public string InvoiceNo { get; set; }
    }
}
